version: '3.8'

services:

  auth-service:
    ports:
      - "5000:5000"
    networks:
      - internal
    build: ./auth-service/

  chat-service:
    expose:
      - "5001"
    networks:
      - internal
    build: ./chat-service
    depends_on:
      - auth-service

networks:
  internal:
    driver: bridge