version: '3.8'

services:

  auth-service:
    expose:
      - "5007"
    networks:
      - internal
    build: ./auth-service

  comment-service:
    expose:
      - "5002"
    networks:
      - internal
    build: ./comment-service
    depends_on:
      - auth-service

  user-service:
    expose:
      - "5003"
    networks:
      - internal
    build: ./user-service
    depends_on:
      - auth-service

  favourite-service:
    expose:
      - "5004"
    networks:
      - internal
    build: ./favourite-service
    depends_on:
      - auth-service

  media-service:
    expose:
      - "5005"
    networks:
      - internal
    build: ./media-service
    depends_on:
      - auth-service

  posts-service:
    expose:
      - "5009"
    networks:
      - internal
    build: ./posts-service
    depends_on:
      - auth-service

  view-service:
    ports:
      - "5000:5000"
    networks:
      - internal
    build: ./view-service
    depends_on:
      - auth-service

networks:
  internal:
    driver: bridge